[FOCUS]
type = "Focus"

[GOAL]
name = "goal_01a"
types = ["Goal", "01", "a"]
sketch = "think about how to get paid"
state = "Fruition.elaboration"

[GOAL_02A]
types = ["Goal", "02", "a"]

[CONTEXT]
type = "Puzzle"

[[_]]
if.CONTEXT.tree = false
s="""
<GOAL> I am {GOAL.name}.
<GOAL.branching> Do you want to {GOAL.sketch}?
    1. Yes
    2. No
"""
[_.1]
s="""
<GOAL.returning.adopting@GOAL> Good.
<GOAL.proposing@GOAL_02A> On to the next, then.
"""
[_.2]
s="""
<GOAL.returning> Suit yourself.
"""
