label = "A single-puzzle stage for RotU"
realm = "rotu"

[[puzzles]]
name = "Tracker Manual page 1"

[puzzles.init]
Fruition = "inception"

[puzzles.state.spot]
van_f_ext =     ["in front of the van"]
van_f_int =     ["in the van"]
van_b_ext =     ["behind the van"]
van_b_int =     ["in the back of the van"]
car_park =      ["car park"]
cafe_f_ext =    ["in front of the cafe"]
shed_f_ext =    ["in front of the shed"]
shed_f_int =    ["inside the shed"]
shed_b_int =    ["back of the shed"]
roadside =      ["by the roadside"]

[[puzzles.items]]
type = "Transit"
states = ["exit.cafe_f_ext", "into.car_park", "Traffic.flowing"]

[[puzzles.items]]
type = "Transit"
states = ["exit.car_park", "into.shed_f_ext", "Traffic.flowing"]

[[puzzles.items]]
type = "Transit"
states = ["exit.shed_f_ext", "into.shed_f_int", "Traffic.flowing"]

[[puzzles.items]]
type = "Transit"
states = ["exit.shed_f_int", "into.shed_b_int", "Traffic.flowing"]

[[puzzles.items]]
type ="Transit"
states = ["exit.car_park", "into.van_f_ext", "Traffic.flowing"]

[[puzzles.items]]
type ="Transit"
states = ["exit.van_f_int", "into.van_b_int", "Traffic.blocked"]

[[puzzles.items]]
type ="Transit"
states = ["exit.van_f_int", "into.van_f_ext", "Traffic.flowing"]

[[puzzles.items]]
type ="Transit"
states = ["exit.van_b_int", "into.van_b_ext", "Traffic.flowing"]

[[puzzles.items]]
type ="Transit"
states = ["exit.van_b_ext", "into.car_park", "Traffic.flowing"]

[[puzzles.items]]
names = ["Door", "Van door"]
type = "Door"
aspect = "unlocked"
sketch = "The {0.name} is {aspect}"
states = ["exit.van_f_ext", "into.van_f_int", "Traffic.flowing"]
