[GOAL]
name = "goal_24a"
types = ["Goal", "24", "a"]
sketch = "drive the van back home"

[GOAL_02A]
types = ["Goal", "02", "a"]
state = "Fruition.completion"

[[_]]
s="""
<GOAL> I am {GOAL.name}. {GOAL.sketch}
"""
