[FOCUS]
type = "Focus"

[GOAL]
name = "goal_00a"
types = ["Goal", "00", "a"]
sketch = "figure out where you are"
state = "Fruition.elaboration"

[GOAL_01A]
types = ["Goal", "01", "a"]

[CONTEXT]
type = "Interaction"

[[_]]
if.CONTEXT.tree = false
s="""
<GOAL> I am {GOAL.name}.
<GOAL.branching> Do you want to {GOAL.sketch}?
    1. Yes
    2. No
<GOAL> Or you can ask for `info`.
"""
[_.1]
s="""
<GOAL.returning.declaring@GOAL> Good.
<GOAL.proposing@GOAL_01A> On to the next, then.
"""
[_.2]
s="""
<GOAL.returning> [Suit yourself](#punchline).
<?label=punchline> And I know you will!
"""
