[GOAL]
name = "goal_02a"
types = ["Goal", "02", "a"]
sketch = "drop off in Archenfield"
state = "Fruition.elaboration"

[GOAL_01A]
types = ["Goal", "01", "a"]
state = "Fruition.completion"

[DRAMA]
type = "Interaction"

[[_]]
if.DRAMA.tree = false
s="""
<GOAL> I am {GOAL.name}.
<GOAL.branching> Do you want to {GOAL.sketch}?
    1. Yes
    2. No
"""
[_.1]
s="""
<GOAL.returning.declaring@GOAL> Good.
"""
[_.2]
s="""
<GOAL.returning> Suit yourself.
"""
